---
title: "PhenologyAnalysis"
author: "RPK"
date: "May 27, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(plyr)
library(dplyr)
library(nlme)
library(gnm)
library(MuMIn)
#library(car)

source("../04ProcessingCode/BackgroundFunctions/AnalysisFunctions_GRMort.R")
source("../04ProcessingCode/BackgroundFunctions/RegressionFuncs.R")

options(stringsAsFactors = FALSE)

#Names
years <- c(12, 13, 14, 15)

#Ecoregion data
ecoregdat <- read.csv("../01ExampleRawData/02LocationData/EcoregionData.csv")
ecoregions <- unique(ecoregdat$EcoregionShort)

#Sources
sources <- unique(ecoregdat$Source)

```

## Add Data to Dataset

Need to add the climate, ecoregion, and distance data


```{r}
#Data with different Distances

#Data with climatic variables
DistClimData <- read.csv("../01ExampleRawData/02LocationData/LocClim.csv")

PhenData<- read.csv("../01ExampleRawData/01CondGrowthPhen/SF_Phen_AlldataRaw.csv")

```

##Data Analysis Section


__Multiple Regression__


```{r}
##For the overal regression
ctrl <- lmeControl(opt='optim')

paramlist <- c("Ecoregion", "Lat", "Long", "Elev", "eFFP",
               "MSP", "Slope", "Aspect", "DD.5.sp")

func_num <- 1:length(paramlist)

for (phen in 1:3) {
  #storing the AIC values and the parameter names
  AIC_list <- c()
  AICnm_list <- c()
  
  if (phen == 1){
    phen_nm <- "Bud.Swollen"
  } else if (phen == 2){
    phen_nm <- "Bud.Elongating"
  } else if (phen == 3) {
    phen_nm <- "Leaves.emerging"
  }
  
  DepVarInd <- match(phen_nm, colnames(PhenData))
  RandVar <- match("Block", colnames(PhenData))
  
  layer1_nums <- func_num
  
  for(num_l1 in func_num){
    num_iter = match(num_l1, layer1_nums)
    layer1_nums <- layer1_nums[-num_iter] #ones left to iterate through at this level
    
    ##parameters for regression function
    param_ind <- match(paramlist[num_l1], colnames(PhenData)) #the index for the indep parameter
    
    reg1 <- MultReg3(PhenData, param_ind, DepVarInd, RandVar)
    
    AIC_list <- append(AIC_list, AIC(reg1[[2]]))
    AICnm_list <- c(AICnm_list, paramlist[num_l1])
    
    ##If there is nothing left to add
    if (length(layer1_nums) == 0){
      break
    }
    
    #Move to layer 2 (two variables) #####################################################################
    layer2_nums = layer1_nums #so you have a list you can remove things from 
    for (num_l2 in layer1_nums){
      num_iter = match(num_l2, layer2_nums)
      layer2_nums <- layer2_nums[-num_iter]
      
      param_n <- c(num_l1, num_l2) #the parameter numbers to use
      p_fullname <- paste(paramlist[param_n], collapse="_") #get the parameter names
      
      params_ind <- match(paramlist[param_n], colnames(PhenData))
      
      reg2 <- MultReg3(PhenData, params_ind, DepVarInd, RandVar)
      
      #Save the AIC values
      AIC_list <- append(AIC_list, AIC(reg2[[2]]))
      AICnm_list <-append(AICnm_list, p_fullname)
      
      ##If there is nothing left to add
      if (length(layer2_nums) == 0){
        break
      }
      
      ##Move to layer 3 (three variables)##################################################
      layer3_nums = layer2_nums #so you have a list you can remove things from 
      for(num_l3 in layer2_nums){
        #Get rid of the new parameter from further iterations  
        num_iter = match(num_l3, layer3_nums)
        layer3_nums <- layer3_nums[-num_iter]
        param_n <- c(num_l1, num_l2, num_l3) #the parameter numbers to use
        
        #Check for forbidden nums
        # if((forbidden[1] %in% param_n) && (forbidden[2] %in% param_n) && (forbidden[3] %in% param_n)){
        #   next
        # }
        
        p_fullname <- paste(paramlist[param_n], collapse="_") #get the parameter names
        params_ind <- match(paramlist[param_n], colnames(PhenData))
        
        reg3 <- MultReg3(PhenData, params_ind, DepVarInd, RandVar)
        
        #Save the AIC values
        AIC_list <- append(AIC_list, AIC(reg3[[2]]))
        AICnm_list <-append(AICnm_list, p_fullname)
        
        
        ##If there is nothing left to add
        if (length(layer3_nums) == 0){
          break
        }
        
        #Move to layer 4 (four variables)#########################################################
        layer4_nums = layer3_nums #so you have a list you can remove things from 
        for (num_l4 in layer3_nums){
          num_iter = match(num_l4, layer4_nums)
          layer4_nums <- layer4_nums[-num_iter]
          param_n <- c(num_l1, num_l2, num_l3, num_l4) #the parameter numbers to use
          
          # #Check for forbidden nums
          # if((forbidden[1] %in% param_n) && (forbidden[2] %in% param_n) && (forbidden[3] %in% param_n)){
          #   next
          # }
          
          #Do the regression
          
          p_fullname <- paste(paramlist[param_n], collapse="_") #get the parameter names
          params_ind <- match(paramlist[param_n], colnames(PhenData))
          
          reg4 <- MultReg3(PhenData, params_ind, DepVarInd, RandVar)
          
          #Save the AIC values
          AIC_list <- append(AIC_list, AIC(reg4[[2]]))
          AICnm_list <-append(AICnm_list, p_fullname)
          
          
          ##If there is nothing left to add
          if (length(layer4_nums) == 0){
            break
          }
          
          #Move to layer 5 (five variables)#########################################################
          layer5_nums = layer4_nums #so you have a list you can remove things from 
          for(num_l5 in layer4_nums){
            num_iter = match(num_l5, layer5_nums)
            layer5_nums <- layer5_nums[-num_iter]
            
            param_n <- c(num_l1, num_l2, num_l3, num_l4, num_l5) #the parameter numbers to use
            
            # #Check for forbidden nums
            # if((forbidden[1] %in% param_n) && (forbidden[2] %in% param_n) && (forbidden[3] %in% param_n)){
            #   next
            # }
            
            #Do the regression
            
            p_fullname <- paste(paramlist[param_n], collapse="_") #get the parameter names
            params_ind <- match(paramlist[param_n], colnames(PhenData))
            
            reg5 <- MultReg3(PhenData, params_ind, DepVarInd, RandVar)
            
            #Save the AIC values
            AIC_list <- append(AIC_list, AIC(reg5[[2]]))
            AICnm_list <-append(AICnm_list, p_fullname)
            
            ##If there is nothing left to add
            if (length(layer5_nums) == 0){
              break
            }
            
            #Move to layer 6######################################################################
            layer6_nums = layer5_nums #so you have a list you can remove things from 
            for(num_l6 in layer5_nums){
              num_iter = match(num_l6, layer6_nums)
              layer6_nums <- layer6_nums[-num_iter]
              param_n <- c(num_l1, num_l2, num_l3, num_l4, num_l5, num_l6) #the parameter numbers to use
              
              #Do the regression
              p_fullname <- paste(paramlist[param_n], collapse="_") #get the parameter names
              params_ind <- match(paramlist[param_n], colnames(PhenData))
              
              reg6 <- MultReg3(PhenData, params_ind, DepVarInd, RandVar)
              
              #Save the AIC values
              AIC_list <- append(AIC_list, AIC(reg6[[2]]))
              AICnm_list <-append(AICnm_list, p_fullname)
              
              ##If there is nothing left to add
              if (length(layer6_nums) == 0){
                break
              }
              
              #Move to layer 7######################################################################
              layer7_nums = layer6_nums #so you have a list you can remove things from 
              for(num_l7 in layer6_nums){
                num_iter = match(num_l7, layer7_nums)
                layer7_nums <- layer7_nums[-num_iter]
                param_n <- c(num_l1, num_l2, num_l3, num_l4, num_l5, num_l6, num_l7) #the parameter numbers to use
                
                #Do the regression
                p_fullname <- paste(paramlist[param_n], collapse="_") #get the parameter names
                params_ind <- match(paramlist[param_n], colnames(PhenData))
                
                reg7 <- MultReg3(PhenData, params_ind, DepVarInd, RandVar)
                
                #Save the AIC values
                AIC_list <- append(AIC_list, AIC(reg7[[2]]))
                AICnm_list <-append(AICnm_list, p_fullname)
                
                ##If there is nothing left to add
                if (length(layer7_nums) == 0){
                  break
                }
                
                #Move to layer 8######################################################################
                layer8_nums = layer7_nums #so you have a list you can remove things from 
                for(num_l8 in layer7_nums){
                  num_iter = match(num_l8, layer8_nums)
                  layer8_nums <- layer8_nums[-num_iter]
                  param_n <- c(num_l1, num_l2, num_l3, num_l4, num_l5, num_l6, num_l7, num_l8) #the parameter numbers to use
                  
                  #Do the regression
                  p_fullname <- paste(paramlist[param_n], collapse="_") #get the parameter names
                  params_ind <- match(paramlist[param_n], colnames(PhenData))
                  
                  reg8 <- MultReg3(PhenData, params_ind, DepVarInd, RandVar)
                  
                  #Save the AIC values
                  AIC_list <- append(AIC_list, AIC(reg8[[2]]))
                  AICnm_list <-append(AICnm_list, p_fullname)
                  
                  ##If there is nothing left to add
                  if (length(layer8_nums) == 0){
                    break
                  }
                  
                  #Move to layer 9######################################################################
                  layer9_nums = layer8_nums #so you have a list you can remove things from 
                  for(num_l9 in layer8_nums){
                    num_iter = match(num_l9, layer9_nums)
                    layer9_nums <- layer9_nums[-num_iter]
                    param_n <- c(num_l1, num_l2, num_l3, num_l4, num_l5, num_l6, num_l7, num_l8, num_l9) #the parameter numbers to use
                    
                    #Do the regression
                    p_fullname <- paste(paramlist[param_n], collapse="_") #get the parameter names
                    params_ind <- match(paramlist[param_n], colnames(PhenData))
                    
                    reg9 <- MultReg3(PhenData, params_ind, DepVarInd, RandVar)
                    
                    #Save the AIC values
                    AIC_list <- append(AIC_list, AIC(reg9[[2]]))
                    AICnm_list <-append(AICnm_list, p_fullname)
                    
                    ##If there is nothing left to add
                    if (length(layer9_nums) == 0){
                      break
                    }
                    
                  } #end layer 9
                } #end layer 8
                
              } # end layer 7
            } #end layer 6
            
          } #end layer 5
          
        } #end layer 4
        
      } #end layer 3
      
    } #end layer 2
    
  } #end layer 1
  
  print(paste("Results for", phen_nm))
  
  min_aic <- min(AIC_list)
  within2_aic <- AIC_list[AIC_list < (min_aic + 2)]
  within2_names <- AICnm_list[AIC_list < (min_aic + 2)]
  
  print(within2_aic)
  print(within2_names)
  
  if(phen ==1){
    nrows = length(within2_aic)
    Phen_AICmat <- matrix(NA, nrow=nrows, ncol=3) 
    colnames(Phen_AICmat) <- c("Phen", "IndepVars", "AIC")
    Phen_AICmat[,1] <- rep(phen_nm, nrows)
    Phen_AICmat[,2] <- within2_names
    Phen_AICmat[,3] <- within2_aic
    
  } else {
    nrows = length(within2_aic)
    
    #Rather convoluted way to add the matrices together
    oldAICmat = Phen_AICmat
    Phen_AICmat = matrix(NA, nrow = length(oldAICmat[,1]) + nrows, ncol = length(oldAICmat[1,]))
    colnames(Phen_AICmat) = colnames(oldAICmat)
    
    Phen_AICmat[,1] <- append(oldAICmat[,1], rep(phen_nm, nrows))
    Phen_AICmat[,2] <- append(oldAICmat[,2], within2_names)
    Phen_AICmat[,3] <- append(oldAICmat[,3], within2_aic)
  }
  
} #end the loop for each phenology type

write.csv(Phen_AICmat, "../05ProcessedDataOutputs/PhenBestMultReg.csv")
```


__In Depth Multiple Regression Results__

```{r}
regdata <- as.data.frame(Phen_AICmat)
paramlist <- c("Ecoregion", "Lat", "Long", "Elev", "eFFP", "MSP", "Slope", "Aspect", "DD.5.sp")

####NEED TO ADAPT THE FOLLOWING

for (phen in 1:3) {#For each response variable 
  
  #which dependent variable you have 
  if (phen == 1){
    dvarnm <- "Bud.Swollen"
  } else if (phen == 2){
    dvarnm <- "Bud.Elongating"
  } else if (phen == 3) {
    dvarnm <- "Leaves.emerging"
  }
  
  DepVarInd <- match(dvarnm, colnames(PhenData))
  
  
  TotNumIndep <- 0
  TotIndepNm <- c()
  
  ##Initialize parameter lists
  aic_vals <- c()
  r2m_vals <- c()
  r2c_vals <- c()
  
  upper_int <- c()
  lower_int <- c()
  est_param <- c()
  p_vals <- c()
  
  ##Site index and pertinent regressions
  
  pert_regs <- regdata[(regdata$Phen == dvarnm),] #find the regressions for that variable
  reg_nms <- c()
  
  for (reg in 1:length(pert_regs[,1])){ #For each regression
    
    indep_vars <- unlist(strsplit(pert_regs[reg, 2], "_")) #split the variables up 
    indep_ind <- match(indep_vars, colnames(PhenData)) #get the indexes for the independent variables
    indep_func_ind <- match(indep_vars, paramlist) #get the index for their function types
    
    ##Add the names of/number of independent variables to the corresponding lists
    for (var in indep_vars){
      
      if (var == "Ecoregion"){
        TotNumIndep <- TotNumIndep + 6 #for all the ecoregions
        TotIndepNm <- append(TotIndepNm, c("CSCD", "CSCO", "KLMT", "PULO", "SRNA", "WIVA"))
        reg_nms <- append(reg_nms, rep(pert_regs[reg, 2], 6))
      } else {
        TotNumIndep <- TotNumIndep + 1
        TotIndepNm <- append(TotIndepNm, var)
        reg_nms <- append(reg_nms, pert_regs[reg, 2])
      }
    }
    
    RandVar <- match("Block", colnames(PhenData)) #random variable
    
    reg_results <- MultReg3(PhenData, indep_ind, DepVarInd, RandVar)
    
    reg_df <- reg_results[[1]] #the dataframe
    reg_obj <- reg_results[[2]] #the lme object
    
    reg_sum <- summary(reg_obj)
    reg_r2 <- r.squaredGLMM(reg_obj) 
    reg_int <- intervals(reg_obj, which = "fixed")
    
    aic_vals <- append(aic_vals, reg_sum$AIC)
    r2m_vals <- append(r2m_vals, reg_r2[1])
    r2c_vals <- append(r2c_vals, reg_r2[2])
    
    num_pert_rws <- length(reg_int$fixed[,1])
    num_indep <- length(indep_vars) + 1 #last index for independent variables to pay attention to 
    upper_int <- append(upper_int, as.vector(reg_int$fixed[2:num_pert_rws,3]))
    lower_int <- append(lower_int, as.vector(reg_int$fixed[2:num_pert_rws,1]))
    est_param <- append(est_param, as.vector(reg_int$fixed[2:num_pert_rws,2]))
    p_vals <- append(p_vals, as.vector(reg_sum$tTable[2:num_pert_rws,5]))
    
    #######DO a QQ PLOT
    print(paste("QQ Plot for", pert_regs[reg, 2], "for phen:", phen))
    qq_plot <- qqnorm(reg_obj) 
    print(qq_plot)
    
    #Heteroskedasticity
    print(paste("Fitted vs Residual Plot for", pert_regs[reg, 2], "for phen:", phen))
    het_plot <- plot(reg_obj) 
    print(het_plot)
    
  } #for each regression 
  
  if (phen==1){
    
    #Overall Model Matrix
    nrowsOverall = length(pert_regs[,1])
    
    o_cols <- c("Dep", "Indep", "Rand", "AIC", "R2m", "R2c")
    overal_mod <- matrix(NA, nrow = nrowsOverall, ncol = length(o_cols))
    colnames(overal_mod) <- o_cols
    
    overal_mod[,1] <- rep(dvarnm, nrowsOverall)
    overal_mod[,2] <- pert_regs[, 2]
    overal_mod[,3] <- rep("Block", nrowsOverall)
    overal_mod[,4] <- aic_vals
    overal_mod[,5] <- r2m_vals
    overal_mod[,6] <- r2c_vals
    
    
    #Parameter Matrix
    nrowsParam <- TotNumIndep
    
    param_cols <- c("Overal_Indep", "Dep", "Spec_Indep", "Estimate", "Lower", "Upper", "P_val")
    param_mat <- matrix(NA, nrow = nrowsParam, ncol = length(param_cols))
    colnames(param_mat) = param_cols
    
    param_mat[,1] <- reg_nms
    param_mat[,2] <- rep(dvarnm, nrowsParam)
    param_mat[,3] <- TotIndepNm
    param_mat[,4] <- est_param
    param_mat[,5] <- lower_int
    param_mat[,6] <- upper_int
    param_mat[,7] <- p_vals
    
  } else { #depending on which Phenological Var you're on
    
    #Rather convoluted way to add the matrices together
    
    ##Overall Matrix
    nrowsOverall = length(pert_regs[,1]) + length(overal_mod[,1])
    nrows_nw <- length(pert_regs[,1])
    oldOveralmat = overal_mod
    
    o_cols <- c("Dep", "Indep", "Rand", "AIC", "R2m", "R2c")
    overal_mod <- matrix(NA, nrow = nrowsOverall, ncol = length(o_cols))
    colnames(overal_mod) <- o_cols
    
    overal_mod[,1] <- append(oldOveralmat[,1], rep(dvarnm, nrows_nw))
    overal_mod[,2] <- append(oldOveralmat[,2], pert_regs[, 2])
    overal_mod[,3] <- append(oldOveralmat[,3], rep("Block", nrows_nw))
    overal_mod[,4] <- append(oldOveralmat[,4], aic_vals)
    overal_mod[,5] <- append(oldOveralmat[,5], r2m_vals)
    overal_mod[,6] <- append(oldOveralmat[,6], r2c_vals)
    
    
    ##Parameter Matrix
    nrowsParam <- TotNumIndep + length(param_mat[,1])
    oldParammat = param_mat
    
    param_cols <- c("Overal_Indep", "Dep", "Spec_Indep", "Estimate", "Lower", "Upper", "P_val")
    param_mat <- matrix(NA, nrow = nrowsParam, ncol = length(param_cols))
    colnames(param_mat) = param_cols
    
    param_mat[,1] <- append(oldParammat[,1], reg_nms)
    param_mat[,2] <- append(oldParammat[,2], rep(dvarnm, TotNumIndep))
    param_mat[,3] <- append(oldParammat[,3], TotIndepNm)
    param_mat[,4] <- append(oldParammat[,4], est_param)
    param_mat[,5] <- append(oldParammat[,5], lower_int)
    param_mat[,6] <- append(oldParammat[,6], upper_int)
    param_mat[,7] <- append(oldParammat[,7], p_vals)
    
  } #depending on which Phenological Var you're on
  

  
} #dependent variable for loop 

  ##Write data to CSV
   write.csv(overal_mod, "../05ProcessedDataOutputs/Phen_BestModelResults.csv")
   write.csv(param_mat, "../05ProcessedDataOutputs/Phen_BestParamResults.csv")

```